version: '3.9'

services:
  celery:
    container_name: celery
    env_file: ${ENV_FILE}
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./app:/app
    networks:
      - ergopad-net
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    # command: tail /dev/null -f
    command: celery -A tasks.celery worker -l ${CELERY_LOGLEVEL} -c 2 -n worker@${WORKER_NAME} -Q ${CELERY_QUEUE} -E # -f logs/celery.log #--without-heartbeat --without-gossip --without-mingle

  celerybeat:
    container_name: celerybeat
    env_file: ${ENV_FILE}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    networks: 
      - ergopad-net
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    command: celery -A beat.celery beat -l ${CELERY_LOGLEVEL} # -f logs/celerybeat.log

  pgmaint:
    container_name: pgmaint
    image: postgres:alpine
    env_file: ${ENV_FILE}
    working_dir: /app
    volumes:
      - /backups/pgmaint:/backups
      - ./periodic/daily:/etc/periodic/daily/:ro
    networks: 
      - ergopad-net
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    profiles: 
      - beta
    command: tail /dev/null -f

  celeryui:
    container_name: celeryui
    env_file: ${ENV_FILE}
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8004:8000
    volumes: 
      - ./app:/app
    networks: 
      - ergopad-net
    profiles: 
      - disabled
    command: uvicorn main:app --host 0.0.0.0 --reload

networks:
  ergopad-net:
    external: true
